# Generated by Django 3.2.19 on 2023-08-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('language', models.CharField(choices=[('nepali', 'Nepali'), ('english', 'English'), ('other', 'Other')], max_length=10)),
                ('country', models.CharField(choices=[('nepal', 'Nepal'), ('india', 'India'), ('china', 'China'), ('other', 'Other')], max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='user_images/')),
            ],
        ),
    ]
